### ISSUE TITLE
Library does not provide reliable transport for messages

### ISSUE THREAD

**Issue by IgorPelevanyuk** [myDevicesIoT/Cayenne-MQTT-Python#10]
First of all. Thank you for the nice library and tool! It is working fine most of the time but under some conditions I cant make it send messages. The following code may allow you repeating the problem.

```
import cayenne.client
import time

# Sleep time in seconds
SLEEP_TIME = 600

MQTT_USERNAME  = "LOREM"
MQTT_PASSWORD  = "LOREM"
MQTT_CLIENT_ID = "LOREM"

client = cayenne.client.CayenneMQTTClient()
client.begin(MQTT_USERNAME, MQTT_PASSWORD, MQTT_CLIENT_ID)

count = 0
timestamp = 0
i=10

while True:
    try:
        client.loop()
        if (time.time() > timestamp + 10):
            client.celsiusWrite(1, i)
            client.virtualWrite(2, i*10%80)
            timestamp = time.time()
            i = i+1
            time.sleep(SLEEP_TIME)

    except Exception, e:
        print e

```

Problem 1(Short SLEEP_TIME ~ 10 sec). First message never gets to myDevices and I cant see it on the graph. So the first data I see in the browser are temperature 11 and humidity 30.
It looks like the library start sending the message, see that something wrong with connection and create it. All the data sent during this process are lost. The next and the following deliveries are fine.

Problem 2(Long SLEEP_TIME ~ 10min). No messages are delivered to myDevices at all. It looks like connection is alive and operational during limited amount of time. 

For me it looks like client.loop() do not create connection(despite the code). It looks like sending checks the connection and if not it creates it for the cost of one set of messages.

**Comment by jburhenn** [comment]
The issue is that client.loop() needs to be called regularly to keep the connection alive and process MQTT messages including connection messages. So adding a delay in the loop can prevent it from running properly at intervals. So instead of using a delay you should use some kind of time to only send data at appropriate times. This is what the ```if (time.time() > timestamp + 10):``` statement is for. So for your situation I would try something like this:

```
import cayenne.client
import time

# Sleep time in seconds
SLEEP_TIME = 10

MQTT_USERNAME  = "LOREM"
MQTT_PASSWORD  = "LOREM"
MQTT_CLIENT_ID = "LOREM"

client = cayenne.client.CayenneMQTTClient()
client.begin(MQTT_USERNAME, MQTT_PASSWORD, MQTT_CLIENT_ID)

count = 0
timestamp = time.time()
i=10

while True:
    try:
        client.loop()
        if (time.time() > timestamp + SLEEP_TIME):
            client.celsiusWrite(1, i)
            client.virtualWrite(2, i*10%80)
            timestamp = time.time()
            i = i+1

    except Exception, e:
        print e
```

If that doesn't work and you still have issues you can try checking with the [Cayenne Community](http://community.mydevices.com/) to see if they may have a solution.

**Comment by IgorPelevanyuk** [comment]
Thank you for the answer. It does not solve the problem but it explains it. 
My point was to use client.celsiusWrite() after blocking function (like serial.read() or sleep()) inside while look. And as far as I can see now this is not possible in single threaded application.

**Comment by jburhenn** [comment]
Yeah, the ```loop()``` function needs to be called at intervals in a single threaded application. So to block you'd need to somehow still call ```loop()``` in a custom blocking function. Or you could maybe try making a threaded version where ```loop()``` is called on its own thread.
